import { CreditCard } from "@/types";

export const CREDIT_CARDS: CreditCard[] = [
  {
    id: "chase-sapphire-preferred",
    name: "Chase Sapphire Preferred",
    issuer: "Chase",
    annualFee: 95,
    annualCredits: [
      { description: "$50 annual hotel credit (Chase Travel)", value: 50 },
    ],
    rewardType: "points",
    pointValue: 1.25,
    baseRewardRate: 1,
    rewards: [
      { category: "dining", rate: 3, type: "points" },
      { category: "travel", rate: 2, type: "points" },
      { category: "streaming", rate: 3, type: "points" },
      { category: "online_grocery", rate: 3, type: "points" },
    ],
    signupBonus: { value: 750, spendRequired: 4000, timeframeDays: 90 },
    notes: "Strong all-around travel card with broad bonus categories and transfer partners.",
    imageUrl: "https://images.ctfassets.net/8qmz0ef3xzub/7iFzyweepMTrfGn2VrDdL5/6adcc35d50cef1e3087ced153d3b7bee/sapphire_preferred_card.png",
  },
  {
    id: "chase-sapphire-reserve",
    name: "Chase Sapphire Reserve",
    issuer: "Chase",
    annualFee: 550,
    annualCredits: [
      { description: "$300 annual travel credit", value: 300 },
      { description: "Priority Pass lounge access", value: 50 },
    ],
    rewardType: "points",
    pointValue: 1.5,
    baseRewardRate: 1,
    rewards: [
      { category: "dining", rate: 3, type: "points" },
      { category: "travel", rate: 5, type: "points" },
    ],
    signupBonus: { value: 900, spendRequired: 4000, timeframeDays: 90 },
    notes: "Premium card with $300 travel credit. Best for heavy travelers who'll use the lounge access.",
    imageUrl: "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/sapphire_reserve_card_Halo.png",
  },
  {
    id: "amex-gold",
    name: "American Express Gold Card",
    issuer: "American Express",
    annualFee: 325,
    annualCredits: [
      { description: "$120 dining credit (Grubhub, Cheesecake Factory, etc.)", value: 120 },
      { description: "$120 Uber Cash ($10/month)", value: 120 },
      { description: "$100 Resy credit", value: 100 },
      { description: "$84 Dunkin' credit", value: 84 },
    ],
    rewardType: "points",
    pointValue: 2.0,
    baseRewardRate: 1,
    rewards: [
      { category: "dining", rate: 4, type: "points" },
      { category: "grocery", rate: 4, type: "points" },
      { category: "travel", rate: 3, type: "points" },
    ],
    signupBonus: { value: 1200, spendRequired: 6000, timeframeDays: 180 },
    notes: "Dominant card for dining and groceries. Credits largely offset the annual fee for active users.",
    imageUrl: "https://cdn.prodstatic.com/shared/images/cards/278x175/87ce2390-9d21-11ef-9a6e-b1df6310cacd.png",
  },
  {
    id: "amex-platinum",
    name: "American Express Platinum",
    issuer: "American Express",
    annualFee: 695,
    annualCredits: [
      { description: "$200 airline fee credit", value: 200 },
      { description: "$200 hotel credit (Fine Hotels + Resorts)", value: 200 },
      { description: "$200 Uber Cash ($15/month + $20 Dec)", value: 200 },
      { description: "$189 CLEAR Plus credit", value: 189 },
      { description: "$100 Saks Fifth Avenue credit", value: 100 },
      { description: "$300 Equinox credit", value: 300 },
      { description: "Global Entry / TSA PreCheck credit (~$25/yr amortized)", value: 25 },
      { description: "Centurion & Priority Pass lounge access", value: 75 },
    ],
    rewardType: "points",
    pointValue: 2.0,
    baseRewardRate: 1,
    rewards: [
      { category: "travel", rate: 5, type: "points" },
      { category: "flights", rate: 5, type: "points" },
    ],
    signupBonus: { value: 1800, spendRequired: 8000, timeframeDays: 180 },
    notes: "Ultra-premium card. Credits ($1,289+) far exceed the fee — but only if you'll actually use them.",
    imageUrl: "https://cdn.prodstatic.com/shared/images/cards/278x175/96987490-949f-11f0-832a-f3f3309a1b0c.png",
  },
  {
    id: "citi-double-cash",
    name: "Citi Double Cash",
    issuer: "Citi",
    annualFee: 0,
    annualCredits: [],
    rewardType: "cashback",
    baseRewardRate: 2,
    rewards: [],
    notes: "Simple 2% cash back on everything (1% when you buy, 1% when you pay). No annual fee.",
    imageUrl: "https://cdn.prodstatic.com/shared/images/cards/278x175/912a9490-aea0-11ec-81f6-95945bae99c9.jpg",
  },
  {
    id: "capital-one-venture-x",
    name: "Capital One Venture X",
    issuer: "Capital One",
    annualFee: 395,
    annualCredits: [
      { description: "$300 annual travel credit (Capital One Travel)", value: 300 },
      { description: "10,000 anniversary bonus miles (~$100 value)", value: 100 },
      { description: "Priority Pass & Capital One lounge access", value: 50 },
      { description: "Global Entry / TSA PreCheck credit (~$25/yr amortized)", value: 25 },
    ],
    rewardType: "miles",
    pointValue: 1.0,
    baseRewardRate: 2,
    rewards: [
      { category: "travel", rate: 10, type: "miles" },
      { category: "hotels", rate: 10, type: "miles" },
      { category: "rental_cars", rate: 5, type: "miles" },
    ],
    signupBonus: { value: 750, spendRequired: 4000, timeframeDays: 90 },
    notes: "Credits and anniversary miles effectively make this card free for most travel spenders.",
    imageUrl: "https://cdn.prodstatic.com/shared/images/cards/278x175/b9dcebc0-eb11-11f0-b6c9-5977dd789339.png",
  },
  {
    id: "discover-it",
    name: "Discover it Cash Back",
    issuer: "Discover",
    annualFee: 0,
    annualCredits: [],
    rewardType: "cashback",
    baseRewardRate: 1,
    rewards: [{ category: "rotating", rate: 5, type: "cashback" }],
    notes: "5% on rotating quarterly categories, 1% elsewhere. Discover matches all cash back earned in year 1.",
    imageUrl: "https://cdn.prodstatic.com/shared/images/cards/278x175/494190c0-6f82-11ef-88db-67757e6c8737.png",
  },
  {
    id: "blue-cash-preferred",
    name: "Blue Cash Preferred (Amex)",
    issuer: "American Express",
    annualFee: 95,
    annualCredits: [
      { description: "$84 Disney Bundle credit ($7/month)", value: 84 },
    ],
    rewardType: "cashback",
    baseRewardRate: 1,
    rewards: [
      { category: "grocery", rate: 6, type: "cashback" },
      { category: "streaming", rate: 6, type: "cashback" },
      { category: "transit", rate: 3, type: "cashback" },
      { category: "gas", rate: 3, type: "cashback" },
    ],
    signupBonus: { value: 250, spendRequired: 3000, timeframeDays: 180 },
    notes: "Best cash back card for grocery shoppers. 6% at US supermarkets (up to $6,000/year).",
    imageUrl: "https://cdn.prodstatic.com/shared/images/cards/278x175/ede1f860-726a-11e9-ad1f-e3d0fefdcf91.png",
  },
  {
    id: "chase-freedom-unlimited",
    name: "Chase Freedom Unlimited",
    issuer: "Chase",
    annualFee: 0,
    annualCredits: [],
    rewardType: "cashback",
    baseRewardRate: 1.5,
    rewards: [
      { category: "dining", rate: 3, type: "cashback" },
      { category: "drugstore", rate: 3, type: "cashback" },
      { category: "travel", rate: 5, type: "cashback" },
    ],
    signupBonus: { value: 200, spendRequired: 500, timeframeDays: 90 },
    notes: "No annual fee with 1.5% base rate. Excellent as a companion to other Chase cards.",
    imageUrl: "https://images.ctfassets.net/8qmz0ef3xzub/302fEMopacO8lPIOANH1Kr/92aa401d22ec4244b1521a02d9ea1e19/freedom_unlimited_card_alt.png",
  },
  {
    id: "wells-fargo-active-cash",
    name: "Wells Fargo Active Cash",
    issuer: "Wells Fargo",
    annualFee: 0,
    annualCredits: [],
    rewardType: "cashback",
    baseRewardRate: 2,
    rewards: [],
    signupBonus: { value: 200, spendRequired: 500, timeframeDays: 90 },
    notes: "Flat 2% cash back on all purchases with no annual fee.",
    imageUrl: "https://cdn.prodstatic.com/shared/images/cards/278x175/8ff39f90-5a56-11ef-a7c5-db9b566f392d.png",
  },
];
